
const products={
  audiovisual:{
    barato:{name:'DJI Neo / Mini 4 Pro',price:'Desde S/ 1,099 – S/ 3,990',img:'assets/images/products/dji-mini-4-pro.webp',badge:'Audiovisual eficiente',why:'Para tu caso, conviene empezar con un drone compacto, estable y fácil de operar. Es suficiente para contenido comercial, inmobiliarias, redes y viajes. Si buscas más calidad de imagen o sesiones largas, comparamos una opción superior y podemos armarte un kit con filtros ND, baterías y maletín.',specs:[['4K','Video'],['Portátil','Operación'],['Rápido','Contenido']],alts:[['DJI Neo','entrada más económica para redes'],['DJI Mini 4 Pro','mejor equilibrio para creator'],['DJI Air 3S','salto profesional de cámara']]},
    caro:{name:'DJI Air 3S',price:'Desde S/ 5,190',img:'assets/images/products/dji-air-3s.webp',badge:'Audiovisual avanzado',why:'Tu objetivo apunta a producción profesional. Conviene una opción con mejor cámara, autonomía y margen para trabajos pagados. Podemos cotizar el drone solo o un kit completo para grabar desde el primer día con baterías, filtros ND y transporte.',specs:[['1” CMOS','Sensor'],['46 min','Autonomía'],['Pro','Producción']],alts:[['DJI Mini 4 Pro','más portable'],['DJI Air 3S','mejor balance pro'],['DJI Avata 2','para tomas FPV dinámicas']]}
  },
  ingenieria:{
    barato:{name:'DJI Mavic 3 Enterprise',price:'Cotizar paquete enterprise',img:'assets/images/products/mavic-3-enterprise.webp',badge:'Ingeniería eficiente',why:'Tu caso necesita datos, inspección o mapeo, pero sin saltar todavía a una plataforma pesada. La ruta correcta es una solución Enterprise eficiente, con posibilidad de sumar RTK, baterías, maletín y orientación de flujo técnico.',specs:[['RTK','Precisión'],['Mapeo','Datos'],['B2B','Operación']],alts:[['Mavic 3 Enterprise','entrada técnica'],['Mavic 3 Thermal','inspección térmica'],['Matrice 4E','más capacidad enterprise']]},
    caro:{name:'DJI Matrice 4E / 350 RTK',price:'Cotizar solución completa',img:'assets/images/products/matrice-4e.webp',badge:'Ingeniería avanzada',why:'Tu operación exige precisión, continuidad y escalabilidad. Conviene evaluar Matrice o una solución Enterprise avanzada. Antes de cotizar, revisamos si necesitas compra, kit técnico, sensor especializado o servicio con operador aliado.',specs:[['RTK','Alta precisión'],['Enterprise','Escalable'],['Sensores','Especializados']],alts:[['Matrice 4E','ingeniería compacta'],['Matrice 350 RTK','plataforma robusta'],['Zenmuse L2','LiDAR / topografía']]}
  },
  agricultura:{
    barato:{name:'DJI Mavic 3 Multispectral',price:'Cotizar paquete agro',img:'assets/images/products/mavic-3-multispectral.webp',badge:'Agricultura eficiente',why:'Tu ruta agrícola parece orientada a diagnóstico y monitoreo. Conviene evaluar multispectral para analizar cultivos y tomar decisiones antes de invertir en aplicación pesada. Podemos orientarte entre compra, servicio o solución agro aliada.',specs:[['NDVI','Cultivos'],['Mapeo','Campo'],['Agro','Diagnóstico']],alts:[['Mavic 3M','monitoreo multispectral'],['Agras T25','aplicación compacta'],['Agras T50','máxima cobertura']]},
    caro:{name:'DJI Agras T25 / T50',price:'Cotizar por hectáreas',img:'assets/images/products/agras-t50.webp',badge:'Agricultura avanzada',why:'Tu operación apunta a aplicación agrícola, fumigación o cobertura de hectáreas. Conviene evaluar Agras según hectáreas, cultivo, baterías, carga y soporte operativo. Es una compra técnica: primero revisamos tu caso y luego cotizamos.',specs:[['Campo','Aplicación'],['Hectáreas','Cobertura'],['Agro','Productividad']],alts:[['Agras T25','operación compacta'],['Agras T50','mayor cobertura'],['Mavic 3M','monitoreo previo']]}
  },
  asesoria:{
    barato:{name:'Asesoría Studio VR',price:'Recomendación personalizada',img:'assets/images/products/dji-neo.webp',badge:'Asesoría',why:'Marcaste que aún no estás seguro. Lo más inteligente es comparar 2 o 3 modelos según tu rubro, presupuesto y uso real antes de comprar.',specs:[['2-3','Opciones'],['Sin sobrecompra','Filtro'],['WhatsApp','Asesoría']],alts:[['Audiovisual','si buscas contenido'],['Ingeniería','si necesitas datos'],['Agricultura','si trabajas campo']]},
    caro:{name:'Asesoría Enterprise Studio VR',price:'Cotización a medida',img:'assets/images/products/matrice-350-rtk.webp',badge:'Asesoría enterprise',why:'Tu caso necesita una revisión más técnica. Conviene cotizar por objetivo, accesorios, entrenamiento, soporte, garantía y flujo de trabajo.',specs:[['B2B','Proyecto'],['Demo','Disponible'],['Soporte','Técnico']],alts:[['Matrice','ingeniería'],['Agras','agricultura'],['Air 3S','producción audiovisual']]}
  }
};
let step=0;const total=5;const answers={};
const qs=[...document.querySelectorAll('.question')], bars=[...document.querySelectorAll('.bar')], prev=document.getElementById('prev'), next=document.getElementById('next'), label=document.getElementById('stepLabel'), nav=document.getElementById('quizNav'), result=document.getElementById('result');
function render(){qs.forEach((q,i)=>q.classList.toggle('active',i===step));bars.forEach((b,i)=>{b.classList.toggle('active',i===step);b.classList.toggle('done',i<step)});label.textContent=String(step+1).padStart(2,'0')+' / 05';prev.style.visibility=step===0?'hidden':'visible';next.textContent=step===total-1?'Ver resultado →':'Siguiente →'}
document.querySelectorAll('.option').forEach(btn=>{btn.addEventListener('click',()=>{const q=btn.closest('.question');q.querySelectorAll('.option').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');answers[btn.dataset.key]=btn.dataset.value;if(step<total-1){setTimeout(()=>{step++;render()},140)}})});
prev.addEventListener('click',()=>{if(step>0){step--;render()}});
next.addEventListener('click',()=>{const q=qs[step];let selected=q.querySelector('.option.selected');if(!selected){selected=q.querySelector('.option');selected.classList.add('selected');answers[selected.dataset.key]=selected.dataset.value}if(step<total-1){step++;render()}else showResult()});
function labelType(t){return ({audiovisual:'Audiovisual',ingenieria:'Ingeniería',agricultura:'Agricultura',asesoria:'Asesoría'})[t]||'Asesoría'}
function labelBudget(b){return b==='caro'?'Presupuesto avanzado':'Presupuesto eficiente'}
function labelLevel(l){return ({basico:'inicio / básico',profesional:'profesional / comercial',tecnico:'técnico avanzado',campo:'campo / operación'})[l]||'por definir'}
function labelExperience(e){return ({inicio:'usuario que está empezando',intermedio:'usuario con experiencia',equipo:'equipo que necesita soporte',empresa:'compra para empresa'})[e]||'usuario por definir'}
function finalType(){let t=answers.type||'asesoria'; if(answers.level==='tecnico') t='ingenieria'; if(answers.level==='campo') t='agricultura'; return t}
function finalBudget(){let b=answers.budget||'barato'; if(answers.level==='tecnico'||answers.level==='campo'||answers.experience==='equipo'||answers.experience==='empresa') b='caro'; if(answers.budget==='barato' && answers.level==='basico') b='barato'; return b}
function showResult(){const t=finalType(), b=finalBudget(), p=products[t][b];document.getElementById('resultBadge').textContent=p.badge;document.getElementById('resultImg').src=p.img;document.getElementById('resultImg').alt=p.name;document.getElementById('resultName').textContent=p.name;document.getElementById('resultPrice').textContent=p.price;document.getElementById('resultWhy').textContent=p.why;document.getElementById('resultProfile').textContent=`${labelType(t)} · ${labelBudget(b)}`;document.getElementById('resultIntentLine').textContent=`Perfil: ${labelLevel(answers.level)} · ${labelExperience(answers.experience)}. Siguiente paso: ${answers.intent==='demo'?'demo o asesoría':answers.intent==='cotizar'?'cotización por WhatsApp':answers.intent==='comparar'?'comparar modelos':'recomendación inicial'}.`;document.getElementById('resultSpecs').innerHTML=p.specs.map(s=>`<div class="spec"><b>${s[0]}</b><span>${s[1]}</span></div>`).join('');document.getElementById('alts').innerHTML=p.alts.map(a=>`<div class="alt"><b>${a[0]}</b><small>${a[1]}</small></div>`).join('');const msg=`Hola Studio VR, hice el Drone Finder. Mi perfil fue ${labelType(t)} con ${labelBudget(b)}. Resultado: ${p.name}. Necesito ${answers.intent||'asesoría'}.`;document.getElementById('waResult').href='https://wa.me/51976075630?text='+encodeURIComponent(msg);document.getElementById('quiz').classList.add('hidden');nav.classList.add('hidden');document.getElementById('progress').classList.add('hidden');result.classList.add('active');result.scrollIntoView({behavior:'smooth',block:'center'});}
document.getElementById('restart').addEventListener('click',()=>{Object.keys(answers).forEach(k=>delete answers[k]);document.querySelectorAll('.option.selected').forEach(b=>b.classList.remove('selected'));step=0;document.getElementById('quiz').classList.remove('hidden');nav.classList.remove('hidden');document.getElementById('progress').classList.remove('hidden');result.classList.remove('active');render();document.getElementById('finder').scrollIntoView({behavior:'smooth'});});
render();
